apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: example-workflow
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: alpine:latest
        command: [sh, -c]
        args:
          - echo "Hello, this is a simple workflow."
